package pojo;

// default package
// Generated 2012-2-15 21:21:54 by Hibernate Tools 3.4.0.CR1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private Grade grade;
	private String name;
	private String passwd;
	private String hobby;
	private String spic;
	private String tel;

	public Student() {
	}

	public Student(int id) {
		this.id = id;
	}

	public Student(Grade grade, String name, String passwd, String hobby,
			String spic, String tel) {
		this.grade = grade;
		this.name = name;
		this.passwd = passwd;
		this.hobby = hobby;
		this.spic = spic;
		this.tel = tel;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public String getSpic() {
		return this.spic;
	}

	public void setSpic(String spic) {
		this.spic = spic;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public void setHobby(String[] hobbys) {
		String hobbyStr = "";
		for (String string : hobbys) {
			hobbyStr += string + ",";
		}
		hobby.substring(0, hobby.length() - 1);
		this.hobby = hobbyStr;
	}

}
